openapi: 3.0.0
info:
  title: Employee API
  version: 1.0.0
servers:
- url: /
paths:
  /employees:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/EmployeeDTO'
                type: array
          description: Úspěšná odpověď
        "204":
          description: Obsah nenalezen
      summary: Vrátí všechny zaměstnance
      x-accepts: application/json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeDTO'
          description: Úspěšná odpověď
      summary: Přidá zaměstnance
      x-content-type: application/json
      x-accepts: application/json
  /employees/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeDTO'
          description: Úspěšná odpověď
        "404":
          description: Zaměstnanec nenalezen
      summary: Smaže zaměstnance podle ID
      x-accepts: application/json
    get:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeDTO'
          description: Úspěšná odpověď
        "404":
          description: Zaměstnanec nenalezen
      summary: Vrátí zaměstnance podle ID
      x-accepts: application/json
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeDTO'
          description: Úspěšná odpověď
        "400":
          description: Zaměstnanec s daným ID nebyl nalezen
      summary: Aktualizuje zaměstnance
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    EmployeeDTO:
      example:
        name: name
        id: 0
        dateBirth: 2000-01-23
        email: email
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        email:
          type: string
        dateBirth:
          format: date
          type: string
      type: object

